name: My first GitHub Actions
on: push
jobs:
    first_job:
        runs-on: ubuntu-24.04
        steps:
            - name: Hello message in Ubuntu VM
              run: echo -e "\e[32mHello Github Actions\e[0m"

            - name: Print working directory
              run: pwd

            - name: List all root files
              run: ls -la /