name: My first GitHub Actions
on: push
jobs:
  first_job:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo # git clones our repo into the ubuntu vm
        uses: actions/checkout@v6.0.2

      - name: Hello message in Ubuntu VM
        run: echo "Hello Github Actions" # how to run a command in ubuntu vm terminal
        
      - name: Where am i?
        run: | # run multiple commands in the ubuntu vm terminal
          pwd
          tree -a -I .git

      - name: Read the README.md file
        run: cat README.md # display the contents of this repo's readme

      # - name: Use 3rd party library tool in ubuntu to create ascii artwork
      #   run: cowsay "Hello CI/CD and GitHub Actions" 
