name: Fetch runner's system information
on: push
jobs:
  system_info:
    runs-on: ubuntu-latest
    steps:
      - name: Listing all files in this repo
        run: ls -al
        
      - name: Executing bash script
        run: ./check-os
